scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    email:
        enabled: true
        mailer: Symfony\Component\Mailer\MailerInterface
        sender_email: "rjkz.rjk1@mail.ru"
        sender_name: "My Symfony App"
