controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

employees_index:
    path: /employees
    controller: App\Controller\EmployeeController::index

employees_create:
    path: /employees/create
    controller: App\Controller\EmployeeController::create

employees_edit:
    path: /employees/{id}/edit
    controller: App\Controller\EmployeeController::edit
    requirements:
        id: \d+

employees_destroy:
    path: /employees/{id}/delete
    controller: App\Controller\EmployeeController::delete
    methods: [DELETE]
    requirements:
        id: \d+

phone_index:
    path: /phones
    controller: App\Controller\PhoneController::index
    methods: GET

phone_new:
    path: /phone/new
    controller: App\Controller\PhoneController::new
    methods: GET|POST

phone_edit:
    path: /phone/edit/{id}
    controller: App\Controller\PhoneController::edit
    methods: GET|POST
    requirements:
        id: \d+

phone_delete:
    path: /phone/delete/{id}
    controller: App\Controller\PhoneController::delete
    methods: POST
    requirements:
        id: \d+

phone_add_to_user:
    path: /phone/add-to-user/{id}
    controller: App\Controller\PhoneController::addToUser
    methods: GET|POST
    requirements:
        id: \d+

user_delete:
    path: /user/delete/{id}
    controller: App\Controller\PhoneController::deleteUser
    methods: POST
    requirements:
        id: \d+

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: [GET]

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

app_profile_update:
    path: /profile/update
    controller: App\Controller\ProfileController::updateProfile
    methods: [POST]

app_resend_2fa:
    path: /resend-2fa-code
    controller: App\Controller\SecurityController::resendTwoFactorCode
    methods: [POST]

app_2fa_settings:
    path: /profile/2fa-settings
    controller: App\Controller\ProfileController::twoFactorSettings
    methods: [GET, POST]

settings_show:
    path: /settings
    controller: App\Controller\SettingController::show
    methods: GET

apartment_index:
    path: /apartments
    controller: App\Controller\ApartmentController::index
    methods: GET

apartment_new:
    path: /apartment/new
    controller: App\Controller\ApartmentController::new
    methods: [GET, POST]

apartment_show:
    path: /apartment/{id}
    controller: App\Controller\ApartmentController::show
    methods: GET

apartment_edit:
    path: /apartment/{id}/edit
    controller: App\Controller\ApartmentController::edit
    methods: [GET, POST]

apartment_delete:
    path: /apartment/{id}
    controller: App\Controller\ApartmentController::delete
    methods: POST

app_credit_calculator:
    path: /credit-calculator
    controller: App\Controller\CreditCalculatorController::index

app_support:
    path: /support
    controller: App\Controller\SupportController::index
    methods: [GET, POST]

app_admin_support:
    path: /admin/support
    controller: App\Controller\SupportController::adminSupport
    methods: [GET]

app_admin_support_reply:
    path: /admin/support/{id}/reply
    controller: App\Controller\SupportController::replyToMessage
    methods: [POST]

app_chat:
    path: /chat
    controller: App\Controller\ChatController::index
    methods: [GET, POST]

app_admin_chat:
    path: /admin/chat
    controller: App\Controller\AdminChatController::index
    methods: [GET]

app_admin_chat_view:
    path: /admin/chat/{id}
    controller: App\Controller\AdminChatController::viewChat
    methods: [GET, POST]